#!/bin/bash
#
## inputs:
## filename (fd 3)
## prefix (fd 4)
## go (fd 5)
#
## outputs:
## <none> - causes side-effect of mv'ing prefix/filename to ./_posts/
#
./debug-entry "[$1] $0"
read filename </dev/fd/3
read prefix </dev/fd/4
read go </dev/fd/5
./rewrite-with-comments "${filename}"
if [ "${go}" == "go" ]
then
    basename=`basename "${filename}"`
echo mv "${filename}" "../_posts/${prefix}-${basename}"
    mv "${filename}" "../_posts/${prefix}-${basename}"
fi
./debug-exit "[$1] $0"


