#!/bin/bash
./debug-entry "[$1] $0"

#
## inputs:
## filename (fd 3)
## content (fd 4) N/C
## go (fd 5)
#
## outputs:
## <none> - side-effect - file.html moved to ./_posts/<prefix>_filename.html
#

wire1=wire_pB_1
wire1a=wire_pB_1a
wire1b=wire_pB_1b
wire2=wire_pB_2
wire2a=wire_pB_2a
wire2b=wire_pB_2b
wire3=wire_pB_3
wire4=wire_pB_4
wire5=wire_pB_5
mkfifo ${wire1} ${wire1a} ${wire1b} ${wire2} ${wire2a} ${wire2b} ${wire3} ${wire4} ${wire5}

./wire-splitter2 "x [$1] $0" 3<${wire1} 4>${wire1a} 5>${wire1b} &
./wire-splitter2 "y [$1] $0" 3<${wire2} 4>${wire2a} 5>${wire2b} &
./create-file-prefix-from-subdir "[$1] $0" 3<${wire1a} 4<${wire2a} 5>${wire3} 6>${wire5}&
./edit-and-move-with-images "[$1] $0" 3<${wire1b} 4<${wire3} 5<${wire2b} 6<${wire5} &

read filename </dev/fd/3
echo "${filename}" > ${wire1} &

read content </dev/fd/4
echo "${content}" > ${wire4} &
./nc 3<${wire4} &

read pin_go </dev/fd/5
echo "${pin_go}" > ${wire2} &

./debug-exit "[$1] $0"
wait

