#!/bin/bash
set -x
# usage: rewrite-with-comments $1
# overwrites $1 with modified html
# creates a tmp file in the process
tmp=`mktemp`
sed -e 's@</body>@<script src="https://utteranc.es/client.js" \
        repo="guitarvydas/guitarvydas.github.io" \
        issue-term="pathname" \
        theme="github-light" \
        crossorigin="anonymous" \
        async> \
</script> \
</body>@' <"${1}" >$tmp
cp $tmp "${1}"
