#!/bin/bash
set -v
./clean
./whitebox-test-move-to-posts
./clean
./whitebox-test-create-file-prefix
./clean
./whitebox-test-isADirectory
./clean
./whitebox-test-wire-splitter2
./clean
./whitebox-test-pathA
./clean
./whitebox-test-pathA-fail
./clean
./whitebox-test-scrivener-to-jekyll
